name: Greeting from ABC
on: push
jobs:
  my-job:
   name: My Job
   runs-on: ubuntu-latest
   steps:
   - name: Print a greeting
     env:
       MY_VAR: Hi there! My name is
       FIRST_NAME: A
       MIDDLE_NAME: B
       LAST_NAME: C
     run: |
       echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
